name: Daily Crime Data Update

on:
  schedule:
    - cron: "0 2 * * *"  # 7:30AM IST
  workflow_dispatch:

jobs:
  update-crime-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        run: node scraper.js

      - name: Commit & Push
        run: |
          git config --global user.name 'GitHub Bot'
          git config --global user.email 'actions@github.com'
          git add crimes.json
          git commit -m "🤖 Auto-update crimes.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
